version: '3'

services:  
  crawlee:
    build:
      context: .
      dockerfile: docker/crawlee/Dockerfile
    ports:
      - "5900:5900"  # VNC port
      - "6080:6080"  # Web interface port (NoVNC)
      - "6079:6079"  # Web interface port (NoVNC)      
    volumes:
      - ./src:/app
      - /dev/shm:/dev/shm  # To improve Chrome's performance\
      - /tmp/.X11-unix:/tmp/.X11-unix  # For X11 forwarding (if needed)
      #- /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      #- /var/run/docker.sock:/var/run/docker.sock  # If you need Docker access inside the container
    working_dir: /app  # Set /app as the working directory inside the container
    environment:
      - DISPLAY=:1  # Ensure it matches the VNC server display
    shm_size: 1gb
    command: node ./index.js
    entrypoint: /startup.sh && /entrypoint-prep-playwright.sh && /bin/bash


    
  # browser:
  #   build: ./docker/browser
  #   ports:
  #     - "5900:5900"  # VNC port
  #     - "6080:6080"  # Web interface port
  #   volumes:
  #     - /dev/shm:/dev/shm  # To improve Chrome's performance
  #   environment:
  #     - VNC_PASSWORD=password123  # Set a password for VNC
  #   cap_add:
  #     - SYS_ADMIN
  #   shm_size: 1gb

    